name: Github Actions Demo
run-name: {{ github.actor }} is testing GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub Actions:
    runs-on: ubuntu-latest
    steps:
    - run: echo "ğŸ‰ The job was automatically triggered by {{ github.event_name }} event."
    - run: echo "ğŸ§ The job is now running on {{ runner.os }} server hosted by GitHub!."
    - run: echo "ğŸ” The name of your branch if {{ github.ref }} and your repository is {{ github.repository }}."
    - name: Check out respoistory code
    - uses: actions/checkout@v4
    - run: "ğŸ’¡ The GitHub repository {{ github.repository }} has been cloned to the runner."
    - run: "ğŸ–¥ï¸ The workflow is now ready to test on your repository."
    - name: "List files in the directory"
    - run: |
        ls {{ github.workspace }}
    - run: "ğŸ This job's status is {{ job.status }}."
